name: Hello World Python CI

on: 
  push: 
    branches: 
      - main 
  pull_request:  #Syntax Error 1
    branches: 
      - main 

jobs: 
  build: 
    runs-on: ubuntu-latest #SyntaxError 2

    steps: 
    - name: Checkout Code 
      uses: actions/checkout@v2 

    - name: Set Up Python 
      uses: actions/setup-python@v2 
      with: 
        python-version: '3.8' 

    - name: Upgrade pip and Install Dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pytest

    - name: Lint Code with Flake8 
      run: | 
        flake8 . 

    - name: Run Tests with Pytest 
      run: | 
        pytest
